name: pfe_salim
description: Mobile Frontend of PfeSalim.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI/UX
  provider: ^6.0.5
  loader_overlay: ^2.1.0
  flutter_spinkit: ^5.1.0

  # LANGUAGE
  intl: ^0.18.0
  flag: ^6.0.0

  # NETWORKING & STORAGE
  http: ^0.13.5
  http_parser: ^4.0.2
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.18
  path_provider: ^2.0.14

  # MEDIA
  mime: ^1.0.4
  image_picker: ^0.8.7
  file_picker: ^5.3.0

  # Charts
  syncfusion_flutter_gauges: ^21.1.37

  # OTHERS
  collection: any

dev_dependencies:
  flutter_launcher_icons: ^0.13.1 # flutter pub run flutter_launcher_icons
  translations_cleaner: ^0.0.5 # dart run translations_cleaner list-unused-terms
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"